POST http://localhost:3000/register
Content-Type: application/json

{
    "username":"ajit_yadav",
    "email":"ajit@gmail.com",
    "password":"ajit_123"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"ajit_yadav",
    "password":"ajit_123"
}

###

POST http://localhost:3000/forget-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFqaXRfeWFkYXYiLCJpYXQiOjE2Nzk3NDM0NjN9.gPhbye583PC-UZL6V9o4_jK3Ok-OlxFcajcJe-ALKMU

{
    "username":"ajit_yadav",
    "email":"ajit@gmail.com"
}


###

GET http://localhost:3000/post/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFqaXRfeWFkYXYiLCJpYXQiOjE2Nzk3NDM0NjN9.gPhbye583PC-UZL6V9o4_jK3Ok-OlxFcajcJe-ALKMU


###

GET http://localhost:3000/post/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFqaXRfeWFkYXYiLCJpYXQiOjE2Nzk3NDM0NjN9.gPhbye583PC-UZL6V9o4_jK3Ok-OlxFcajcJe-ALKMU

###

POST http://localhost:3000/add-post/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFqaXRfeWFkYXYiLCJpYXQiOjE2Nzk3NDM0NjN9.gPhbye583PC-UZL6V9o4_jK3Ok-OlxFcajcJe-ALKMU

{
    "postId":8,
    "postContent":"Help receive certainly case",
    "commentContent":"Remember country",
    "reactionType":"LIKE",
    "postedAt":"2023-01-10 15:09:32"
}

###

PUT http://localhost:3000/update-post/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFqaXRfeWFkYXYiLCJpYXQiOjE2Nzk3NDM0NjN9.gPhbye583PC-UZL6V9o4_jK3Ok-OlxFcajcJe-ALKMU

{
    "postContent":"Design clear grow lot",
    "commentContent":"Should language hot get law",
    "reactionType":"DISLIKE",
    "postedAt":"2023-01-10 15:09:32"
}

###

DELETE http://localhost:3000/delete-post/8/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFqaXRfeWFkYXYiLCJpYXQiOjE2Nzk3NDM0NjN9.gPhbye583PC-UZL6V9o4_jK3Ok-OlxFcajcJe-ALKMU


###

GET http://localhost:3000/recent-post/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFqaXRfeWFkYXYiLCJpYXQiOjE2Nzk3NDM0NjN9.gPhbye583PC-UZL6V9o4_jK3Ok-OlxFcajcJe-ALKMU